### PR TITLE
ability to load images from non local FS sources

### PR DESCRIPTION
**Pull request by iamgoroot**
I needed to load images from github

### CODE REVIEW

**Comment by tenkoh** [comment]
Thank you for your PR!
I need some time to review it, please wait.

**Comment by tenkoh** [comment]
Hi, @iamgoroot 
Your proposal is great! To improve it, I want to discuss with you.

Following your PR, users would prepare their own `FileReader` to read remote images. I suppose it is as below.
```go
func FileReader(s string) ([]byte, error) {
    c := http.DefaultClient
    resp, _ := c.Get(s)
    defer resp.Body.Close()
    return io.ReadAll(resp.Body)
}
```

How about receiving just `*http.Client` in the new option? Users would like to custom `*http.Client` (ex. Timeout) but they would not like to custom getting and reading data method.

I tried a simple example as below.

```diff
type Img64Config struct {
	html.Config
	ParentPath   string
+	RemoteReader *http.Client
}
```
```go
func (r *img64Renderer) readRemoteImage(path string) ([]byte, error) {
	resp, err := r.RemoteReader.Get(path)
	if err != nil {
		return nil, fmt.Errorf("fail to get %s: %w", path, err)
	}
	defer resp.Body.Close()

	b, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("fail to read %s: %w", path, err)
	}
	return b, nil
}
```
```go
func (r *img64Renderer) encodeImage(src []byte) ([]byte, error) {
	s := string(src)
	// already encoded
	if strings.HasPrefix(s, "data:") {
		return src, nil
	}

	var reader func(string) ([]byte, error)
	if strings.HasPrefix(s, "http://") || strings.HasPrefix(s, "https://") {
		if r.RemoteReader == nil {
			return src, nil // do not encode remote images by default
		}
		reader = r.readRemoteImage
	} else {
		reader = r.readLocalImage
	}

	b, err := reader(s)
	if err != nil {
		return nil, fmt.Errorf("can not read image: %w", err)
	}
        // ...
}
```

I'd love to hear your thoughts on this comment! If it resonates with you, it would be great if you could help refine the content of the pull request. Of course, if you're busy, just let me know. 

Thank you.

**Comment by iamgoroot** [comment]
> Hi, @iamgoroot Your proposal is great! To improve it, I want to discuss with you.
> 
> Following your PR, users would prepare their own `FileReader` to read remote images. I suppose it is as below.
> 
> ```go
> func FileReader(s string) ([]byte, error) {
>     c := http.DefaultClient
>     resp, _ := c.Get(s)
>     defer resp.Body.Close()
>     return io.ReadAll(resp.Body)
> }
> ```
> 
> How about receiving just `*http.Client` in the new option? Users would like to custom `*http.Client` (ex. Timeout) but they would not like to custom getting and reading data method.
> 
> I tried a simple example as below.
> 
> ```diff
> type Img64Config struct {
> 	html.Config
> 	ParentPath   string
> +	RemoteReader *http.Client
> }
> ```
> 
> ```go
> func (r *img64Renderer) readRemoteImage(path string) ([]byte, error) {
> 	resp, err := r.RemoteReader.Get(path)
> 	if err != nil {
> 		return nil, fmt.Errorf("fail to get %s: %w", path, err)
> 	}
> 	defer resp.Body.Close()
> 
> 	b, err := io.ReadAll(resp.Body)
> 	if err != nil {
> 		return nil, fmt.Errorf("fail to read %s: %w", path, err)
> 	}
> 	return b, nil
> }
> ```
> 
> ```go
> func (r *img64Renderer) encodeImage(src []byte) ([]byte, error) {
> 	s := string(src)
> 	// already encoded
> 	if strings.HasPrefix(s, "data:") {
> 		return src, nil
> 	}
> 
> 	var reader func(string) ([]byte, error)
> 	if strings.HasPrefix(s, "http://") || strings.HasPrefix(s, "https://") {
> 		if r.RemoteReader == nil {
> 			return src, nil // do not encode remote images by default
> 		}
> 		reader = r.readRemoteImage
> 	} else {
> 		reader = r.readLocalImage
> 	}
> 
> 	b, err := reader(s)
> 	if err != nil {
> 		return nil, fmt.Errorf("can not read image: %w", err)
> 	}
>         // ...
> }
> ```
> 
> I'd love to hear your thoughts on this comment! If it resonates with you, it would be great if you could help refine the content of the pull request. Of course, if you're busy, just let me know.
> 
> Thank you.

Just passing http client doesn't cut it in a lot of cases. In my case i'm resolving relative urls from github repo and only then download them
what if markdown is stored somewhere else like ftp or samba?
Would be nicer to bundle few implementations of reader instead of giving inflexible option that solves specific case

**Comment by tenkoh** [comment]
OK, I got it. LGTM.

**Pull request merged**
